POST http://localhost:3000/api/log_energy HTTP/1.1
Content-Type: application/json

{
	"meterId": "1",
	"activePower": 100.0,
	"reactivePower": 50.0,
	"apparentPower": 111.8,
	"voltage": 230.0,
	"current": 0.43,
	"powerFactor": 0.89,
	"phaseAngle": 27.0,
	"frequency": 50.0,
	"consumedEnergy": 0.5,
	"generatedEnergy": 0.0,
	"operationTime": 60.0,
	"rawData": {
		"example_field": "example_value"
    }	
}
    