/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as ChartsRouteImport } from './routes/charts'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiEnergyRouteImport } from './routes/api/energy'
import { Route as ApiEnergyStatsRouteImport } from './routes/api/energy/stats'
import { Route as ApiEnergyMetersRouteImport } from './routes/api/energy/meters'
import { Route as ApiEnergyLogsRouteImport } from './routes/api/energy/logs'
import { Route as ApiEnergyLatestRouteImport } from './routes/api/energy/latest'
import { Route as ApiEnergyConsumptionRouteImport } from './routes/api/energy/consumption'

const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const ChartsRoute = ChartsRouteImport.update({
  id: '/charts',
  path: '/charts',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEnergyRoute = ApiEnergyRouteImport.update({
  id: '/api/energy',
  path: '/api/energy',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEnergyStatsRoute = ApiEnergyStatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => ApiEnergyRoute,
} as any)
const ApiEnergyMetersRoute = ApiEnergyMetersRouteImport.update({
  id: '/meters',
  path: '/meters',
  getParentRoute: () => ApiEnergyRoute,
} as any)
const ApiEnergyLogsRoute = ApiEnergyLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => ApiEnergyRoute,
} as any)
const ApiEnergyLatestRoute = ApiEnergyLatestRouteImport.update({
  id: '/latest',
  path: '/latest',
  getParentRoute: () => ApiEnergyRoute,
} as any)
const ApiEnergyConsumptionRoute = ApiEnergyConsumptionRouteImport.update({
  id: '/consumption',
  path: '/consumption',
  getParentRoute: () => ApiEnergyRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/charts': typeof ChartsRoute
  '/reports': typeof ReportsRoute
  '/api/energy': typeof ApiEnergyRouteWithChildren
  '/api/energy/consumption': typeof ApiEnergyConsumptionRoute
  '/api/energy/latest': typeof ApiEnergyLatestRoute
  '/api/energy/logs': typeof ApiEnergyLogsRoute
  '/api/energy/meters': typeof ApiEnergyMetersRoute
  '/api/energy/stats': typeof ApiEnergyStatsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/charts': typeof ChartsRoute
  '/reports': typeof ReportsRoute
  '/api/energy': typeof ApiEnergyRouteWithChildren
  '/api/energy/consumption': typeof ApiEnergyConsumptionRoute
  '/api/energy/latest': typeof ApiEnergyLatestRoute
  '/api/energy/logs': typeof ApiEnergyLogsRoute
  '/api/energy/meters': typeof ApiEnergyMetersRoute
  '/api/energy/stats': typeof ApiEnergyStatsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/charts': typeof ChartsRoute
  '/reports': typeof ReportsRoute
  '/api/energy': typeof ApiEnergyRouteWithChildren
  '/api/energy/consumption': typeof ApiEnergyConsumptionRoute
  '/api/energy/latest': typeof ApiEnergyLatestRoute
  '/api/energy/logs': typeof ApiEnergyLogsRoute
  '/api/energy/meters': typeof ApiEnergyMetersRoute
  '/api/energy/stats': typeof ApiEnergyStatsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/charts'
    | '/reports'
    | '/api/energy'
    | '/api/energy/consumption'
    | '/api/energy/latest'
    | '/api/energy/logs'
    | '/api/energy/meters'
    | '/api/energy/stats'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/charts'
    | '/reports'
    | '/api/energy'
    | '/api/energy/consumption'
    | '/api/energy/latest'
    | '/api/energy/logs'
    | '/api/energy/meters'
    | '/api/energy/stats'
  id:
    | '__root__'
    | '/'
    | '/charts'
    | '/reports'
    | '/api/energy'
    | '/api/energy/consumption'
    | '/api/energy/latest'
    | '/api/energy/logs'
    | '/api/energy/meters'
    | '/api/energy/stats'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChartsRoute: typeof ChartsRoute
  ReportsRoute: typeof ReportsRoute
  ApiEnergyRoute: typeof ApiEnergyRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/charts': {
      id: '/charts'
      path: '/charts'
      fullPath: '/charts'
      preLoaderRoute: typeof ChartsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/energy': {
      id: '/api/energy'
      path: '/api/energy'
      fullPath: '/api/energy'
      preLoaderRoute: typeof ApiEnergyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/energy/stats': {
      id: '/api/energy/stats'
      path: '/stats'
      fullPath: '/api/energy/stats'
      preLoaderRoute: typeof ApiEnergyStatsRouteImport
      parentRoute: typeof ApiEnergyRoute
    }
    '/api/energy/meters': {
      id: '/api/energy/meters'
      path: '/meters'
      fullPath: '/api/energy/meters'
      preLoaderRoute: typeof ApiEnergyMetersRouteImport
      parentRoute: typeof ApiEnergyRoute
    }
    '/api/energy/logs': {
      id: '/api/energy/logs'
      path: '/logs'
      fullPath: '/api/energy/logs'
      preLoaderRoute: typeof ApiEnergyLogsRouteImport
      parentRoute: typeof ApiEnergyRoute
    }
    '/api/energy/latest': {
      id: '/api/energy/latest'
      path: '/latest'
      fullPath: '/api/energy/latest'
      preLoaderRoute: typeof ApiEnergyLatestRouteImport
      parentRoute: typeof ApiEnergyRoute
    }
    '/api/energy/consumption': {
      id: '/api/energy/consumption'
      path: '/consumption'
      fullPath: '/api/energy/consumption'
      preLoaderRoute: typeof ApiEnergyConsumptionRouteImport
      parentRoute: typeof ApiEnergyRoute
    }
  }
}

interface ApiEnergyRouteChildren {
  ApiEnergyConsumptionRoute: typeof ApiEnergyConsumptionRoute
  ApiEnergyLatestRoute: typeof ApiEnergyLatestRoute
  ApiEnergyLogsRoute: typeof ApiEnergyLogsRoute
  ApiEnergyMetersRoute: typeof ApiEnergyMetersRoute
  ApiEnergyStatsRoute: typeof ApiEnergyStatsRoute
}

const ApiEnergyRouteChildren: ApiEnergyRouteChildren = {
  ApiEnergyConsumptionRoute: ApiEnergyConsumptionRoute,
  ApiEnergyLatestRoute: ApiEnergyLatestRoute,
  ApiEnergyLogsRoute: ApiEnergyLogsRoute,
  ApiEnergyMetersRoute: ApiEnergyMetersRoute,
  ApiEnergyStatsRoute: ApiEnergyStatsRoute,
}

const ApiEnergyRouteWithChildren = ApiEnergyRoute._addFileChildren(
  ApiEnergyRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChartsRoute: ChartsRoute,
  ReportsRoute: ReportsRoute,
  ApiEnergyRoute: ApiEnergyRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
